server:
  port: 9999
spring:
  cloud:
    gateway:
      routes:
        - id: NewsService-eureka
          uri: http://localhost:8081
          predicates:
            - Path=/news/**

        - id: blogApp-eureka
          uri: http://localhost:8082
          predicates:
            - Path=/blog/**

